### ISSUE TITLE
Connection problems with XREADGROUP

### ISSUE THREAD

**Issue by Shir0kamii** [NoneGG/aredis#113]
## Checklist

- Python version: 3.6
- Using hiredis or just Python parser: python parser
- Using uvloop or just asyncio event loop: asyncio
- Does issue exists against the `master` branch of aredis? yes

## Steps to reproduce

Connect to a Redis cluster and try to make XREADGROUP commands

## Expected behavior

Returns messages from the stream

## Actual behavior

First, I was bothered by "TTL exhausted" exceptions, as if aredis wasn't following redirections upon MovedErrors. I came up with a simple fix (which may not be appropried for general case): commenting [that](https://github.com/NoneGG/aredis/blob/83e44c14f03a456f5593765db1fde37bb8554ca0/aredis/client.py#L394) line.

Then, the problem became that after a finite number of XREADGROUP commands, aredis raised an exception "Too many connections". For a given max_connections, the number of commands issued before the exception is always the same. Also, this behaviour is specific to xreadgroup, I can xread without problems.

This makes me think that connections are not released properly with XREADGROUP commands, but I can't see why. What would be your diagnosis ?

Here is the traceback I get:
```
Traceback (most recent call last):
  File "/var/www/metrics-doctor-forwarder/source/forwarder/.venv/lib/python3.6/site-packages/aredis/pool.py", line 501, in get_connection_by_node
    connection = self._available_connections.get(node["name"], []).pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "forwarder/test.py", line 47, in process
    async for msg in stream:
  File "forwarder/test.py", line 35, in stream_listener
    items = await redis_conn.xreadgroup("metrics-doctor-forwarder", "forwarder-single", count=20, status=">")
  File "/var/www/metrics-doctor-forwarder/source/forwarder/.venv/lib/python3.6/site-packages/aredis/commands/streams.py", line 238, in xreadgroup
    return await self.execute_command('XREADGROUP', *pieces)
  File "/var/www/metrics-doctor-forwarder/source/forwarder/.venv/lib/python3.6/site-packages/aredis/utils.py", line 167, in inner
    return await func(*args, **kwargs)
  File "/var/www/metrics-doctor-forwarder/source/forwarder/.venv/lib/python3.6/site-packages/aredis/client.py", line 399, in execute_command
    r = self.connection_pool.get_connection_by_node(node)
  File "/var/www/metrics-doctor-forwarder/source/forwarder/.venv/lib/python3.6/site-packages/aredis/pool.py", line 503, in get_connection_by_node
    connection = self.make_connection(node)
  File "/var/www/metrics-doctor-forwarder/source/forwarder/.venv/lib/python3.6/site-packages/aredis/pool.py", line 394, in make_connection
    raise RedisClusterException("Too many connections")
aredis.exceptions.RedisClusterException: Too many connections
```

**Comment by NoneGG** [comment]
@Shir0kamii I try to reproduce the problem in my dev env(just use redis cluster in docker) but failed, and i found the same issue raised in redis-py-cluster [issue](https://github.com/Grokzen/redis-py-cluster/issues/301)
That may help.

**Comment by szelenka** [comment]
I've come across similar problems occasionallyL
```
ERROR:asyncio:Task exception was never retrieved
--
  | future: <Task finished coro=<Subscriber.run() done, defined at /opt/app-root/src/lib/redis/async_subscriber.py:41> exception=TypeError("object of type 'NoneType' has no len()")>
  | Traceback (most recent call last):
  | File "/opt/app-root/src/lib/redis/async_subscriber.py", line 64, in run
  | last_id = await self.process_stream(last_id=last_id)
  | File "/opt/app-root/src/lib/redis/async_subscriber.py", line 160, in process_stream
  | **{self.stream_key: last_id},
  | File "/usr/local/lib/python3.7/site-packages/aredis/commands/streams.py", line 238, in xreadgroup
  | return await self.execute_command('XREADGROUP', *pieces)
  | File "/usr/local/lib/python3.7/site-packages/aredis/client.py", line 156, in execute_command
  | return await self.parse_response(connection, command_name, **options)
  | File "/usr/local/lib/python3.7/site-packages/aredis/client.py", line 174, in parse_response
  | return callback(response, **options)
  | File "/usr/local/lib/python3.7/site-packages/aredis/commands/streams.py", line 22, in multi_stream_list
  | result[r[0]] = stream_list(r[1])
  | File "/usr/local/lib/python3.7/site-packages/aredis/commands/streams.py", line 12, in stream_list
  | while len(kv_pairs) > 1:
  | TypeError: object of type 'NoneType' has no len()
```

I haven't been able to figure out what would cause a None to be returned from the stream, any thoughts?

**Comment by NoneGG** [comment]
@szelenka It seems to be a different issue, i think your feature request is reasonable, i will see if there is anything i can do

**Comment by NoneGG** [comment]
@szelenka Fixed, please see if this will help
