### ISSUE TITLE
Python 3.8 pip install error: "cannot import name 'CancelledError'"

### ISSUE THREAD

**Issue by psidex** [NoneGG/aredis#122]
## Checklist

- Python version 3.8
- Does issue exists against the `master` branch of aredis? Yes

## Steps to reproduce

`pip install aredis`

## Expected behavior

It installs

## Actual behavior

```
Collecting aredis
  Using cached https://files.pythonhosted.org/packages/26/a6/6df2c18fd3fcefa4ca978679bd280b610e686669efa2a0df53cc172a49a6/aredis-1.1.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Simon\\AppData\\Local\\Temp\\pip-install-qmzu_4f_\\aredis\\setup.py'"'"'; __file__='"'"'C:\\Users\\Simon\\AppData\\Local\\Temp\\pip-install-qmzu_4f_\\aredis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Simon\AppData\Local\Temp\pip-install-qmzu_4f_\aredis\pip-egg-info'
         cwd: C:\Users\Simon\AppData\Local\Temp\pip-install-qmzu_4f_\aredis\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Simon\AppData\Local\Temp\pip-install-qmzu_4f_\aredis\setup.py", line 6, in <module>
        from aredis import __version__
      File "C:\Users\Simon\AppData\Local\Temp\pip-install-qmzu_4f_\aredis\aredis\__init__.py", line 1, in <module>
        from aredis.client import (StrictRedis, StrictRedisCluster)
      File "C:\Users\Simon\AppData\Local\Temp\pip-install-qmzu_4f_\aredis\aredis\client.py", line 3, in <module>
        from asyncio.futures import CancelledError
    ImportError: cannot import name 'CancelledError' from 'asyncio.futures' (c:\program files\python38\lib\asyncio\futures.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by NoneGG** [comment]
@psidex This bug is fixed in issue #121 
Doesn't that change take effect?

**Comment by psidex** [comment]
The latest version on [pypi](https://pypi.org/project/aredis/) is `1.1.5` which does not contain that fix.

Is it possible for you to push the update onto there?

**Comment by NoneGG** [comment]
Sure, new version will be released this week

**Comment by NoneGG** [comment]
@psidex release 1.1.6 is public, i will leave this issue open (there may be some other implicit problems i am afraid of) Please try and if there is any problem, let me know and i will fix it as soon as possible~

**Comment by psidex** [comment]
Awesome, thanks 👍

**Comment by bsergean** [comment]
FYI I was able to install the module on python 3.8.0 on my mac.

```
(venv) cobra$ pip install aredis
Collecting aredis
  Downloading https://files.pythonhosted.org/packages/54/6e/086022ccea78fd587303edb271c0c9100a7f65500e83b07bd69a44a4e65d/aredis-1.1.7.tar.gz (128kB)
     |████████████████████████████████| 133kB 10.6MB/s 
Building wheels for collected packages: aredis
  Building wheel for aredis (setup.py) ... done
  Created wheel for aredis: filename=aredis-1.1.7-cp38-cp38-macosx_10_9_x86_64.whl size=90666 sha256=9c38a2d31d3c6475e6cd5a64aa8cbaca6d1641cf88dc99342b546a9808518dee
  Stored in directory: /Users/bsergeant/Library/Caches/pip/wheels/f4/4d/37/5d6f066872f806e09a844d60c231614ff68e0cc792ee90647e
Successfully built aredis
Installing collected packages: aredis
Successfully installed aredis-1.1.7
(venv) cobra$ pip --version
pip 19.3.1 from /Users/bsergeant/src/foss/cobra/venv/lib/python3.8/site-packages/pip (python 3.8)
```
