### ISSUE TITLE
ModuleNotFoundError installing 1.1.6 on Python 3.6

### ISSUE THREAD

**Issue by AdmiralNemo** [NoneGG/aredis#126]
When attempting to install _aredis_ 1.1.6 in a Python 3.6 environment, a `ModuleNotFoundError` is raised:

```
python3.6 -m venv aredis-test
aredis-test/bin/pip install aredis
```

```
Collecting aredis
  Downloading https://files.pythonhosted.org/packages/ff/a5/251ef8a0d5e0c967597dd1141a14342060c2e8d7377f2a562cc1bfe07738/aredis-1.1.6.tar.gz (131kB)
     |████████████████████████████████| 133kB 3.4MB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-enyghb49/aredis/setup.py", line 6, in <module>
        from aredis import __version__
      File "/tmp/pip-install-enyghb49/aredis/aredis/__init__.py", line 1, in <module>
        from aredis.client import (StrictRedis, StrictRedisCluster)
      File "/tmp/pip-install-enyghb49/aredis/aredis/client.py", line 10, in <module>
        from aredis.commands.extra import ExtraCommandMixin
      File "/tmp/pip-install-enyghb49/aredis/aredis/commands/extra.py", line 1, in <module>
        from aredis.lock import Lock, LuaLock
      File "/tmp/pip-install-enyghb49/aredis/aredis/lock.py", line 6, in <module>
        import contextvars
    ModuleNotFoundError: No module named 'contextvars'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-enyghb49/aredis/
```

I think this is happening because the `setup.py` script attempts to import the `aredis` package (to get the version number) before installing any dependencies.

**Comment by NoneGG** [comment]
@AdmiralNemo Thank you for your bug report~ The bug is fixed and version 1.1.7 is released.(considering `VERSION` may be relied on, i have to maintain the version num in two files now)
