### ISSUE TITLE
Invalid version number

### ISSUE THREAD

**Issue by newbie-c** [NoneGG/aredis#156]
Hello, everyone...

I got this trouble with aredis today:

    $ python
    Python 3.8.4rc1 (default, Jul  1 2020, 15:31:45) 
    [GCC 9.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import aredis
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/avm/workspace/aioauriz/venv/lib/python3.8/site-packages/aredis/__init__.py", line 1, in <module>
        from aredis.client import (StrictRedis, StrictRedisCluster)
      File "/home/avm/workspace/aioauriz/venv/lib/python3.8/site-packages/aredis/client.py", line 4, in <module>
        from aredis.commands.cluster import ClusterCommandMixin
      File "/home/avm/workspace/aioauriz/venv/lib/python3.8/site-packages/aredis/commands/cluster.py", line 1, in <module>
        from aredis.utils import (bool_ok,
      File "/home/avm/workspace/aioauriz/venv/lib/python3.8/site-packages/aredis/utils.py", line 17, in <module>
        LOOP_DEPRECATED = StrictVersion(python_version) >= StrictVersion("3.8.0")
      File "/usr/lib/python3.8/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/usr/lib/python3.8/distutils/version.py", line 137, in parse
        raise ValueError("invalid version number '%s'" % vstring)
    ValueError: invalid version number '3.8.4rc1'
    >>> 

It is Debian bullseye, last update of Python3. It worked yesterady, before the update. I know, it is not supported and I am running in front of a steam engine, it is dangerous but I need **aredis**. Any suggestion would be nice... Thanks in advance.

**Comment by thebaptiste** [comment]
Too bad this has not been fixed in a new release...
