### ISSUE TITLE
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by AndrewGPU** [NoneGG/aredis#220]
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/andrew11/lib/python3.11/site-packages/aredis/connection.py", line 415, in connect
    await self._connect()
  File "/home/ubuntu/miniconda3/envs/andrew11/lib/python3.11/site-packages/aredis/connection.py", line 594, in _connect
    reader, writer = await exec_with_timeout(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/andrew11/lib/python3.11/site-packages/aredis/connection.py", line 39, in exec_with_timeout
    return await asyncio.wait_for(coroutine, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/andrew11/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/andrew11/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                         ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'

python = 3.11 
3.10 version seems to be

**Comment by truekonrads** [comment]
@AndrewGPU  see the pull request/branch https://github.com/truekonrads/aredis/tree/loop-deprecated-asybcio-open_connection . Either install from there or wait until aredis maintainer releases a new version.

**Comment by yogevyuval** [comment]
@mjwestcott Is this package still maintained? Do you think Is it possible to have a new release?

**Comment by jaagupku** [comment]
@yogevyuval, seems the package is unmaintained since October of 2020. You should look into coredis, a fork of this project.
https://coredis.readthedocs.io/en/latest/history.html

**Comment by Luferov** [comment]
Any status?

**Comment by sanjusci** [comment]
Any update on this?
