### ISSUE TITLE
Assertion Error Asyncio Socket

### ISSUE THREAD

**Issue by NotSoSuper** [NoneGG/aredis#25]
Getting these errors on Python 3.6

```
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 253, in data_received
    self._stream_reader.feed_data(data)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 413, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
```

My code
```
async def pubsub_loop(self):
	self.pubsub = self.redis.pubsub(ignore_subscribe_messages=True)
	await self.pubsub.subscribe('notsobot.rpc')
	while True:
		message = await self.pubsub.get_message()
		if message:
			load = json.loads(message['data'])
			self.bot.dispatch('rpc_receive', load)
		await asyncio.sleep(0.01)

async def publish(self, payload, snowflake):
	await self.redis.publish('notsobot.rpc', json.dumps({'shard_id': self.bot.shard_id, 'snowflake': snowflake, 'payload': payload}))
```
Not sure right now if it's my code or the library, the error is vague.
Also, everything is working fine, it's just these errors spam my console.

**Comment by NoneGG** [comment]
@NotSoSuper Thank you for your bug report! 

According to your error, it seems like the aredis connection is used after it is closed. So i try to reproduce the error according to code given (i changed some part of it, for example, the bot attribute), but the code runs smoothly, if you don't mind, could you provide code more detailed? 

Or can you tell me how you call `publish()` and `pubsub_loop()`?

My code is like below:

``` Python
import json
import asyncio
import concurrent.futures
from aredis import StrictRedis

class ErrorCase(object):

    def __init__(self):
        self.redis = StrictRedis()
        self.shard_id = 1

    async def pubsub_loop(self):
        self.pubsub = self.redis.pubsub(ignore_subscribe_messages=True)
        await self.pubsub.subscribe('notsobot.rpc')
        for _ in range(10):
            message = await self.pubsub.get_message()
            if message:
                load = json.loads(message['data'])
                print(load)
                # self.bot.dispatch('rpc_receive', load)
            else:
                print('no message')
            await asyncio.sleep(0.01)

    async def publish(self, payload, snowflake):
        await self.redis.publish('notsobot.rpc', json.dumps({'shard_id': self.shard_id, 'snowflake': snowflake, 'payload': payload}))


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    error_case = ErrorCase()
    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
        for _ in range(10):
            executor.submit(asyncio.run_coroutine_threadsafe, error_case.publish(1, 2), loop)
    loop.run_until_complete(error_case.pubsub_loop())


```

**Comment by NotSoSuper** [comment]
That's about all the code I use regarding aredis, the only other part would be in the `rpc_receive` function when I dispatch the event which calls at the end `await self.publish({'command': 'received', 'response': r}, data['snowflake'])`

**Comment by NoneGG** [comment]
@NotSoSuper 
I am not sure, the exception is hard to trace because it is raised from asyncio code and the error can not be reproduced in my environment.
The only clue is the `feed_eof`

In aredis, the read stream is `feed_eof` only when connection is disconnectd, and after being feeded eof, the reader or writer stream will be set to `None` (which disable them to be used again). So it is wierd that the stream is used again after being feeded eof.

If you don't mind, can you help me to find out the line from which the error is raised? It's a good chance to make the code stronger.

**Comment by NoneGG** [comment]
I mean the line of aredis code in which the aredis connection is disconnected and reused again or something related.

**Comment by NoneGG** [comment]
Hey @NotSoSuper , do you have any idea about the bug?  Or may i close this issue?

**Comment by NotSoSuper** [comment]
Sorry for the late response, I've rechecked my code and used try/except blocks but none of them produced an error.

**Comment by NoneGG** [comment]
@NotSoSuper 
Actually i did some experiments to prove my guess, but it seems like my guess is wrong.
 
In code below i try to disconnect the connection directly or use `pubsub.reset` to make the connection disconnected, but still can't the error be reproduced.
``` Python
async def pubsub_loop(self):
        self.pubsub = self.redis.pubsub(ignore_subscribe_messages=True)
        await self.pubsub.subscribe('notsobot.rpc')
        for i in range(10):
            message = await self.pubsub.get_message()
            if message:
                load = json.loads(message['data'])
                print(load)
                # self.bot.dispatch('rpc_receive', load)
            else:
                print('no message')
            if i > 1:
                self.pubsub.connection.disconnect()
                # self.pubsub.reset()
                # await self.pubsub.subscribe('notsobot.rpc')
            await asyncio.sleep(0.01)
```

In `PubSub.parse_response`, if the connection can be read is checked when parsing response
``` Python
async def parse_response(self, block=True):
        "Parse the response from a publish/subscribe command"
        connection = self.connection
        if connection is None:
            raise RuntimeError(
                'pubsub connection not set: '
                'did you forget to call subscribe() or psubscribe()?')
        if not block and not await connection.can_read():
            return None
        return await self._execute(connection, connection.read_response)
```
And the `Connection.can_read` will have a check on whether the connction is feeded eof by using `at_eof` function. If the connection is disconnectd as expected (its reader and writer stream will be set to None and then it will reconnect by `self.connect()` automatically)
``` Python
async def can_read(self):
        "See if there's data that can be read."
        if not (self._reader and self._writer):
            await self.connect()
        return self._parser.can_read() or (not self._reader.at_eof())
```

**Comment by NoneGG** [comment]
@NotSoSuper 
Hey~ Did you use `StrictRedis` or `StrictRedisCluster` as your redis client?
If the bug is raised when you were using `StrictRedisCluster`, there are two bug issues raised by melhin( #26 #28 ) which may lead to your question and is now fixed.
If you don't mind, could you install aredis from github (current version is not released yet) and try it again?

You can install by command 
`pip install git+https://github.com/NoneGG/aredis`

**Comment by NotSoSuper** [comment]
@NoneGG I was using StrictRedis client, I'll update the package and test again!

**Comment by NoneGG** [comment]
@NotSoSuper 
Thanks, but no big changes were made on StrictRedis and the bug may still be there. 
Anyway, i will try my best to figure out the bug.

**Comment by NoneGG** [comment]
@NotSoSuper 
To solve the problem, i discard usage of `feed_eof`(mainly used in `connection.can_read` and pubsub) and use another way to enable `timeout` when using `pubsub and to handle streams disconnection.
[commit](https://github.com/NoneGG/aredis/pull/36/commits/d764804cf75a5e8bdfab4f4e04a6d5cf755f6a77) is here.

I hope that will help to solve the problem, it passes all test in my env and could you help to test in you code please?

**Comment by NotSoSuper** [comment]
It indeed has fixed the issue, thank you! I'll be switching back from aioredis 👍

```python
>>> import aredis
>>> redis = aredis.StrictRedis()
>>> import asyncio
>>> loop = asyncio.get_event_loop()
>>> async def s():
...   pb = redis.pubsub(ignore_subscribe_messages=True)
...   await pb.subscribe('memes.1')
...   while True:
...     msg = await pb.get_message()
...     if msg:
...       print(msg)
...     await asyncio.sleep(1)
... 
>>> loop.run_until_complete(s())
{'type': 'message', 'pattern': None, 'channel': 'memes.1', 'data': '{"lol": "meme"}'}
```

**Comment by NoneGG** [comment]
@NotSoSuper 
Hope that will help you~
If you have other problems about aredis please tell me, i will fix it as soon as i can
